[project]
name = "sila2-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "sila2[codegen]>=0.12.2",
    "structlog>=25.3.0",
]
